### ISSUE TITLE
Premium user tier

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-to-mail#16]
I'm exploring what features would be premium. Likely the following features will be "premium":
- Creating more than 3 searches
- Downloading a CSV of job searches
- Filtering recruiter job listings.

I'd love input on this. I understand that not all users will want to pay so I want to keep a free tier no matter what, but in order to help fund the website I need to find some way to make a few bucks.

**Comment by wondersoftheworld** [comment]
karl, i like the idea of a premium tier package.

**Comment by karllhughes** [comment]
So far I have:

- Implemented three premium features
- Added a landing page at `/premium` that allows users to tell me that they're interested in Premium

Next I need to:

- Add monthly recurring billing so users can activate premium immediately
- Let the system track who is paid and who is not
