### ISSUE TITLE
One click Heroku deploy

### ISSUE THREAD

**Issue by wondersoftheworld** [jobapis/jobs-to-mail#18]
Team, could u kindly provide a one click heroku deploy? Thanks.

**Comment by karllhughes** [comment]
Good idea. Doesn't look like it's too hard to add: https://devcenter.heroku.com/articles/heroku-button

**Comment by karllhughes** [comment]
@wondersoftheworld I'm merging this in today: https://github.com/jobapis/jobs-to-mail/pull/34
