### ISSUE TITLE
suggest 24pullrequests participation

### ISSUE THREAD

**Issue by soleo** [jobapis/jobs-to-mail#28]
@karllhughes 

https://24pullrequests.com is a pretty cool event which encourage users to contribute to open source projects every year in December. It wouldn't hurt to get some help from others. I made a project suggestion on 24pullrequests. I'd encourage you to do it from your account and see how effective it could be.

**Comment by karllhughes** [comment]
Good idea! I'm going to be out of the country for a few weeks away from my comp, but I'll submit it!
