### ISSUE TITLE
Token table migration fails with MySQL database

### ISSUE THREAD

**Issue by maxleaver** [jobapis/jobs-to-mail#30]
The "create_tokens_table" migration fails if you're using a MySql/MariaDB database. It is trying to create an unsigned uuid field, but the field is of type CHAR in MySQL, so can't be unsigned.

I'm happy to create a pull request to remove the unsigned designator from the migration if it's helpful.

**Comment by karllhughes** [comment]
Hey Max, thanks for pointing this out. I've never run the app on MySQL/Maria, so I'm not too surprised it doesn't work quite right. A PR would be welcome!

**Comment by karllhughes** [comment]
Addressed in https://github.com/jobapis/jobs-to-mail/pull/31
