### ISSUE TITLE
List job boards being searched on homepage

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-to-mail#4]
I got some feedback from a user who said it would be helpful to know which job boards are being searched when signing up. I haven't put a ton of thought into this, but maybe we could add a box on the homepage with icons and names of sites that are being searched?

**Comment by karllhughes** [comment]
Currently the project supports:
- [Careerbuilder](http://www.careerbuilder.com/)
- [Careercast](http://www.careercast.com/)
- [Dice](http://www.dice.com/)
- [Github jobs](https://jobs.github.com/)
- [Government jobs](http://search.digitalgov.gov/)
- [Indeed](http://www.indeed.com/)
- [Jobinventory](http://www.jobinventory.com/)
- [Juju](http://www.juju.com/)
- [USAJobs](https://www.usajobs.gov/)
- [Ziprecruiter](https://www.ziprecruiter.com/)

I'll try to keep this issue up to date as I add more providers.

**Comment by soleo** [comment]
A UI like https://babeljs.io/users/ would be nice.

**Comment by karllhughes** [comment]
I like that. Legally I'm not sure if I'm allowed to use their logos though. I probably need to do more research on that.

**Comment by soleo** [comment]
You can always choose to take down the logo if they contact you. Normally you'd have 24 hours to take actions. We used some college logos in exactsports.com, and that's what we did in the past. Obviously, I cannot offer legal advice, but i think it should be okay to use the logos.

**Comment by karllhughes** [comment]
I'm fine with that. Ultimately we're promoting these job boards by sending them new traffic, so I can't imagine it will cause an uproar. Are you interested in making a page with these logos @soleo? Otherwise it's on my backlog, but may take me a while to get to.

**Comment by soleo** [comment]
Sure. No problem. I'll push a PR this weekend or so.

**Comment by karllhughes** [comment]
Cool, I just updated the list of clients we support in the [comment above](https://github.com/jobapis/jobs-to-mail/issues/4#issuecomment-250640778). There are now links to all their official sites there as well.

Thanks!

**Comment by soleo** [comment]
@karllhughes I just did a pull request. If the size of logo is too large, it can be changed easily via the  sketch file I provided. I make a universal size for all logos so that it would look nice on home page, but wasn't sure what would be the right size. Let me know what you thinks?
